"""
Django settings for drtStudy project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kc)7g^pf)afv2+@t!zf2d2b+ls1%dq(0adwk+-#w2qu%stfa$8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book01.apps.BookFirstConfig',
    'book02.apps.BookSecondConfig',
    'book03.apps.BookThreeConfig',
    'goods.apps.GoodsConfig',
    'book04.apps.BookFourConfig',
    'user.apps.UserConfig',
    'book05.apps.BookFiveConfig',
    'book06.apps.Book6Config',
    'book07.apps.Book7Config',
    'book08.apps.Book8Config',
    'book09.apps.Book9Config',
    'book10.apps.Book10Config',
    'book11.apps.Book11Config',
    'book12.apps.Book12Config',
    'book13.apps.Book13Config',
    'book14.apps.Book14Config',
    'book15.apps.Book15Config',
    'book16.apps.Book16Config',
    'book17.apps.Book17Config',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drtStudy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drtStudy.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'mysql',
        'NAME': 'django_study'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIR = [
    os.path.join(BASE_DIR, 'static')
]

# ===========================DRF的一些设置===============================
REST_FRAMEWORK = {
    # DRF框架默认全局认证方式
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     # session认证
    #     'rest_framework.authentication.SessionAuthentication',
    #     # 基本认证
    #     'rest_framework.authentication.BasicAuthentication'
    # ),
    # 权限控制
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    # 全局限流设置(针对匿名用户和认证用户分别进行限流设置)
    # 'DEFAULT_THROTTLE_CLASSES': (
    #     # 针对未登录(匿名)用户的限流控制类
    #     'rest_framework.throttling.AnonRateThrottle',
    #     # 针对登录(认证)用户的限流控制类
    #     'rest_framework.throttling.UserRateThrottle'
    # ),
    # # 指定限流频次
    # 'DEFAULT_THROTTLE_RATES': {
    #     # 认证用户的限流频次
    #     'user': '5/minute',
    #     # 匿名用户的限流频次
    #     'anon': '3/minute',
    # },
    # 针对匿名用户和认证用户进行统一的限流控制
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),

    # 指定限流频次选择项
    'DEFAULT_THROTTLE_RATES': {
        'upload': '3/minute',
        'contacts': '5/minute'
    },

    # 过滤
    # 'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),

    # 全局分页设置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'DEFAULT_PAGINATION_CLASS':  'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 3,  # 每页数目

    # 指定DRF框架的异常处理函数
    'EXCEPTION_HANDLER': 'book16.utils.exceptions.exception_hander',

}
